import { defineConfig } from 'tsup';

export default defineConfig([
  // Library entry — dist/index.js (bundled single file + types)
  {
    entry: { index: 'src/index.ts' },
    format: ['esm'],
    outDir: 'dist',
    dts: {
      resolve: true,
      compilerOptions: {
        composite: false,
        declaration: true,
        declarationMap: true,
        incremental: false,
        ignoreDeprecations: '6.0',
      },
    },
    sourcemap: true,
    clean: true,
    bundle: false,
    external: [
      /^node:/,
      '@huggingface/transformers',
      'web-tree-sitter',
      '@ladybugdb/core',
      'express',
      'cors',
      'commander',
      '@modelcontextprotocol/sdk',
      'graphology',
      'graphology-communities-louvain',
      'code-intel-shared',
      '@anthropic-ai/sdk',
      'openai',
      'compression',
    ],
    treeshake: true,
    splitting: false,
  },
  // Hook entry — dist/cli/hook.js (tiny binary, fast startup ~50ms)
  // Imports ONLY hook-rewriter.ts — no OTel, no DB, no graph.
  {
    entry: { 'cli/hook': 'src/cli/hook.ts' },
    format: ['esm'],
    outDir: 'dist',
    dts: false,
    sourcemap: true,
    clean: false,
    external: [/^node:/],
    treeshake: true,
    splitting: false,
  },
  // CLI app entry — dist/cli/app.js (full CLI implementation)
  {
    entry: { 'cli/app': 'src/cli/app.ts' },
    format: ['esm'],
    outDir: 'dist',
    dts: false,
    sourcemap: true,
    clean: false,
    external: [
      /^node:/,
      '@huggingface/transformers',
      'web-tree-sitter',
      '@ladybugdb/core',
      'express',
      'cors',
      'commander',
      '@modelcontextprotocol/sdk',
      'graphology',
      'graphology-communities-louvain',
      'code-intel-shared',
      '@anthropic-ai/sdk',
      'openai',
      'compression',
    ],
    treeshake: true,
    splitting: false,
  },
  // CLI bootstrap entry — dist/cli/main.js (tiny binary, lazy-loads app)
  {
    entry: { 'cli/main': 'src/cli/main.ts' },
    format: ['esm'],
    outDir: 'dist',
    dts: false,
    sourcemap: true,
    clean: false,
    external: [/^node:/],
    treeshake: true,
    splitting: false,
  },
  // Workflow validation entry — dist/agents/workflows/validate-cli.js (tiny binary,
  // run at build time by scripts in package.json's `build` script). Same minimal
  // self-contained bundling pattern as cli/hook: no OTel, no DB, no graph.
  {
    entry: { 'agents/workflows/validate-cli': 'src/agents/workflows/validate-cli.ts' },
    format: ['esm'],
    outDir: 'dist',
    dts: false,
    sourcemap: true,
    clean: false,
    external: [/^node:/],
    treeshake: true,
    splitting: false,
  },
]);
